export const PETLIST_FETCH_START = 'PETLIST_FETCH_START';
export const PETLIST_FETCH_SUCCESS = 'PETLIST_FETCH_SUCCESS';
export const PETLIST_FETCH_ERROR = 'PETLIST_FETCH_ERROR';

export const PET_FETCH_START = 'PET_FETCH_START';
export const PET_FETCH_SUCCESS = 'PET_FETCH_SUCCESS';
export const PET_FETCH_FAIL = 'PET_FETCH_FAIL';

export const DELETE_PET_START = 'DELETE_PET_START';
export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_FAIL = 'DELETE_PET_FAIL';
export const DELETE_PET_RESET = 'DELETE_PET_RESET';

export const CREATE_PET_START = 'CREATE_PET_START';
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
export const CREATE_PET_FAIL = 'CREATE_PET_FAIL';
export const CREATE_PET_RESET = 'CREATE_PET_RESET';

export const EDIT_PET_START = 'EDIT_PET_START';
export const EDIT_PET_SUCCESS = 'EDIT_PET_SUCCESS';
export const EDIT_PET_FAIL = 'EDIT_PET_FAIL';
export const EDIT_PET_RESET = 'EDIT_PET_RESET';
